
[package]
name = "clingofmt"
version = "0.1.2-dev"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "Tool to find and fix formatting issues in clingo files"
readme = "README.md"
repository = "https://github.com/potassco/clingofmt"
license = "MIT"
edition = "2021"
exclude = ["/.github"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
confy = "0.5"
serde = "^1.0"
serde_yaml = { version = "0.8", optional = true }
serde_derive = "*"
env_logger = "0.11"
tree-sitter = "~0.22.6"
tree-sitter-clingo = "~0.0.14"
